twig:
    file_name_pattern: '*.twig'
    globals:
        google_maps_api_key: '%env(GOOGLE_MAPS_API_KEY)%'
        site_uri: '%env(SITE_URI)%'
    form_themes: ['@TalesFromADevFlowbite/form/default.html.twig']


when@test:
    twig:
        strict_variables: true
