twig:
    file_name_pattern: '*.twig'
    globals:
        mapbox_token: '%env(MAPBOX_TOKEN)%'
    form_themes: ['@TalesFromADevFlowbite/form/default.html.twig']


when@test:
    twig:
        strict_variables: true
